# Future work

When building this application, we wanted to design an application that could serve as big an audience as possible. One possibility would be expanding the location to have a worldwide view of opioid addiction, by gathering information for different countries. Having more data at the county level could also provide more information about what type of areas (rural, large cities, etc.) are common to opioid addiction.

As mentioned previously, the Medicare Part D prescriber data is a large dataset and we have only scratched the surface with the type of information it is showing. A future version of the application could incorporate more of the data, from comparing different years to developing different analysis to see if certain outcomes can be predicted using the variables available.

Other questions we drew from this project, for which we did not have data, were which states have stricter laws against opioids and if that helps contribute to less deaths. With regard to overdoses and deaths from drugs that can be legally prescribed, we would like to know if individuals who died from opioid overdoses, overdosed on prescribed medication or on illegally-obtained opioids, whether heroin or a prescription drug they were not personally prescribed. With the available data we had, this was not a question we can answer, but we feel it would be very useful for researchers investigating this problem.  A recent CDC report (April 24,2019) attempts to correct the misapplication of its guidelines for opioid prescriptions that are currently known to be in practice by providers, including “abrupt tapering and sudden discontinuation” of opioids. The CDC notes that these practices may result in “pain and psychological distress” and may lead to individuals seeking other sources of opioids [@CDCMisapplication].  While these drugs can be dangerous, they do have important uses in improving quality of life for individuals living with chronic pain. After looking at the results within the application where in some states the death rate is increasing, even as the prescriber rate is dropping, we wondered how many individuals with a legitimate need for strong painkillers are obtaining them illegally as prescriber rates drop and if they are overdosing as a result of taking them without being under the care of a physician. We believe access to data about the individuals would be extremely useful, though it may be difficult to obtain due to HIPAA.

A recent story in the news brings a new angle to the opioid crisis - the role of drug manufacturers. On May 2, 2019, ABC news reported on a settlement between Mckesson Corp. and the state of West Virginia over “massive quantities” of opioids supplied to pharmacies in small West Virginia towns. For future work, working with data about the supply-side of these drugs would provide important information for those working to end the crisis [@WVSettlement].
